SET local check_function_bodies = off;

CREATE EXTENSION "pgjwt" SCHEMA "extensions";

CREATE EXTENSION "postgis" SCHEMA "extensions";

CREATE TABLE "public"."attributes_definitions" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"       text   NOT NULL,
  "input_type" text,
  "options"    text[],
  "unit"       text,
  "code"       text   NOT NULL,
  CONSTRAINT "attributes_definitions_code_key" UNIQUE (code),
  CONSTRAINT "attributes_definitions_name_key" UNIQUE (name),
  CONSTRAINT "attributes_definitions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."attributes_definitions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."brand_created_by" (
  "id_brand"   bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "id_user"    uuid,
  CONSTRAINT "brand_created_by_pkey" PRIMARY KEY (id_brand)
);

ALTER TABLE "public"."brand_created_by"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."brand" (
  "id"          bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"        text    NOT NULL,
  "slug"        text    NOT NULL,
  "website"     text,
  "picture"     text,
  "is_verified" boolean DEFAULT false,
  "is_active"   boolean DEFAULT true,
  CONSTRAINT "brand_name_key" UNIQUE (name),
  CONSTRAINT "brand_pkey" PRIMARY KEY (id),
  CONSTRAINT "brand_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."brand"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."category_attribute_rules" (
  "id_category"      bigint  NOT NULL,
  "id_attribute_def" bigint  NOT NULL,
  "required"         boolean NOT NULL,
  CONSTRAINT "category_attribute_rules_pkey" PRIMARY KEY (id_category, id_attribute_def)
);

ALTER TABLE "public"."category_attribute_rules"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."category" (
  "id"          bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"        text    NOT NULL,
  "slug"        text    NOT NULL,
  "description" text,
  "parent_id"   bigint,
  "is_active"   boolean DEFAULT true,
  CONSTRAINT "category_pkey" PRIMARY KEY (id),
  CONSTRAINT "category_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."category"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."certification" (
  "id"          bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"        text    NOT NULL,
  "slug"        text    NOT NULL,
  "description" text,
  "is_active"   boolean DEFAULT true,
  "is_public"   boolean NOT NULL DEFAULT false,
  CONSTRAINT "certification_name_key" UNIQUE (name),
  CONSTRAINT "certification_pkey" PRIMARY KEY (id),
  CONSTRAINT "certification_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."certification"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."conversation_user" (
  "id_user"         uuid                     NOT NULL,
  "id_conversation" bigint                   NOT NULL,
  "joined_at"       timestamp with time zone NOT NULL DEFAULT now(),
  "is_muted"        boolean                  NOT NULL DEFAULT false,
  CONSTRAINT "conversation_user_pkey" PRIMARY KEY (id_user, id_conversation)
);

ALTER TABLE "public"."conversation_user"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."conversation" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "last_updated" time with time zone      NOT NULL DEFAULT now(),
  "status"       text                     NOT NULL DEFAULT 'active'::character varying,
  CONSTRAINT "conversation_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."conversation"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."feed_impressions" (
  "id_user"    uuid                     NOT NULL,
  "id_product" bigint                   NOT NULL,
  "shown_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "feed_impressions_pkey" PRIMARY KEY (id_user, id_product)
);

ALTER TABLE "public"."feed_impressions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."keep_alive" (
  "id"        bigint                   NOT NULL,
  "last_ping" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "keep_alive_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."keep_alive"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."message_attachment" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "file_path"  text,
  "file_type"  text,
  "file_size"  bigint,
  "id_message" bigint,
  CONSTRAINT "message_attachment_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."message_attachment"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."message" (
  "id"                  bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "message_content"     text                     NOT NULL,
  "sent_at"             timestamp with time zone NOT NULL DEFAULT now(),
  "has_attachment"      boolean                  NOT NULL DEFAULT false,
  "reply_to_id_message" bigint,
  "id_conversation"     bigint                   NOT NULL,
  "id_sender"           uuid                     NOT NULL,
  "read_at"             timestamp with time zone DEFAULT now(),
  "id_troc"             bigint,
  CONSTRAINT "message_id_troc_key" UNIQUE (id_troc),
  CONSTRAINT "message_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."message"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."notification" (
  "id"                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type"              text                     NOT NULL,
  "related_entity_id" bigint,
  "body"              text,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "is_read"           boolean                  NOT NULL DEFAULT false,
  "id_user"           uuid,
  CONSTRAINT "notification_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."notification"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."product_attributes" (
  "id_product"              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_attribute_def"        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_attribute_value" text   NOT NULL,
  CONSTRAINT "product_attributes_pkey" PRIMARY KEY (id_product, id_attribute_def, product_attribute_value)
);

ALTER TABLE "public"."product_attributes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."product_location" (
  "product_id" bigint                           NOT NULL,
  "location"   extensions.geography(Point,4326) NOT NULL,
  "city"       text                             NOT NULL,
  "postcode"   text                             NOT NULL,
  "department" text                             NOT NULL,
  "created_at" timestamp with time zone         NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone         NOT NULL DEFAULT now(),
  CONSTRAINT "product_location_city_check" CHECK (((btrim(city) <> ''::text) AND (char_length(city) <= 120))),
  CONSTRAINT "product_location_department_check" CHECK (((btrim(department) <> ''::text) AND (char_length(department) <= 120))),
  CONSTRAINT "product_location_pkey" PRIMARY KEY (product_id),
  CONSTRAINT "product_location_postcode_check" CHECK (((btrim(postcode) <> ''::text) AND (char_length(postcode) <= 20)))
);

ALTER TABLE "public"."product_location"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."product_photos" (
  "id"             bigint   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "url"            text     NOT NULL,
  "order_position" smallint NOT NULL,
  "id_product"     bigint   NOT NULL,
  CONSTRAINT "product_photos_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."product_photos"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."product" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "name"          text                     NOT NULL,
  "description"   text,
  "price_trocoin" integer                  NOT NULL,
  "is_active"     boolean                  NOT NULL DEFAULT true,
  "id_state"      bigint,
  "id_category"   bigint,
  "id_brand"      bigint,
  "id_user"       uuid,
  "share_count"   bigint                   NOT NULL DEFAULT '0'::bigint,
  CONSTRAINT "product_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."product"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reserved_usernames" (
  "username" text NOT NULL,
  CONSTRAINT "reserved_usernames_lowercase_check" CHECK ((username = lower(username))),
  CONSTRAINT "reserved_usernames_pkey" PRIMARY KEY (username)
);

ALTER TABLE "public"."reserved_usernames"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."state" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  "slug" text   NOT NULL,
  CONSTRAINT "state_name_key" UNIQUE (name),
  CONSTRAINT "state_pkey" PRIMARY KEY (id),
  CONSTRAINT "state_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."state"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."troc_product" (
  "id_product" bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_troc"    bigint  NOT NULL,
  "id_owner"   uuid    NOT NULL,
  "is_offered" boolean NOT NULL,
  CONSTRAINT "troc_product_pkey" PRIMARY KEY (id_product, id_troc)
);

ALTER TABLE "public"."troc_product"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."troc_status_history" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "changed_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "previous_status" text                     NOT NULL,
  "new_status"      text                     NOT NULL,
  "changed_by"      uuid,
  "reason"          text,
  "id_troc"         bigint,
  CONSTRAINT "troc_status_history_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."troc_status_history"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."trocoin_transaction" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "amount"       integer                  NOT NULL,
  "id_reference" bigint,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "description"  text,
  "id_user"      uuid,
  CONSTRAINT "trocoin_transaction_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."trocoin_transaction"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."troc" (
  "id"                        bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"                timestamp with time zone NOT NULL DEFAULT now(),
  "status"                    text                     NOT NULL,
  "delivery_method"           text                     NOT NULL,
  "meeting_date"              timestamp with time zone NOT NULL,
  "meeting_location"          extensions.geography,
  "meeting_details"           text,
  "value_is_lower"            boolean,
  "needs_additional_trocoins" boolean                  NOT NULL DEFAULT false,
  "additional_trocoins"       integer,
  "completed_at"              timestamp with time zone,
  "last_updated_at"           timestamp with time zone NOT NULL DEFAULT now(),
  "id_user_initiator"         uuid,
  "id_user_receiver"          uuid,
  CONSTRAINT "troc_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."troc"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_blocks" (
  "blocked_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "id_user_blocker" uuid                     NOT NULL,
  "id_user_blocked" uuid                     NOT NULL,
  CONSTRAINT "user_blocks_pkey" PRIMARY KEY (id_user_blocker, id_user_blocked)
);

ALTER TABLE "public"."user_blocks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_category_preferences" (
  "id_user"     uuid                     NOT NULL,
  "id_category" bigint                   NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_category_preferences_pkey" PRIMARY KEY (id_user, id_category)
);

ALTER TABLE "public"."user_category_preferences"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_certifications" (
  "id_user"           uuid                     NOT NULL,
  "id_certification"  bigint                   NOT NULL,
  "certified_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "verified_by_admin" boolean,
  CONSTRAINT "user_certifications_pkey" PRIMARY KEY (id_user, id_certification)
);

ALTER TABLE "public"."user_certifications"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_evaluations" (
  "id_user_evaluated" uuid                     NOT NULL,
  "id_user_evaluator" uuid                     NOT NULL,
  "id_troc"           bigint                   NOT NULL,
  "id"                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "rating"            smallint                 NOT NULL,
  "comment"           text,
  "evaluated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_evaluations_pkey" PRIMARY KEY (id_user_evaluated, id_user_evaluator, id_troc)
);

ALTER TABLE "public"."user_evaluations"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_follows" (
  "id_user_follower" uuid                     NOT NULL,
  "id_user_followed" uuid                     NOT NULL,
  "followed_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_follows_pkey" PRIMARY KEY (id_user_follower, id_user_followed)
);

ALTER TABLE "public"."user_follows"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_location" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "location"     extensions.geography,
  "last_updated" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_location_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."user_location"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_product_history" (
  "id_user"    uuid                     NOT NULL,
  "id_product" bigint                   NOT NULL,
  "viewed_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_product_history_pkey" PRIMARY KEY (id_user, id_product)
);

ALTER TABLE "public"."user_product_history"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_product_likes" (
  "id_user"    uuid                     NOT NULL,
  "id_product" bigint                   NOT NULL,
  "liked_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_product_likes_pkey" PRIMARY KEY (id_user, id_product)
);

ALTER TABLE "public"."user_product_likes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_product_reports" (
  "id_user"     uuid                     NOT NULL,
  "id_product"  bigint                   NOT NULL,
  "id_report"   bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reason"      text,
  "reported_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_product_reports_pkey" PRIMARY KEY (id_user, id_product)
);

ALTER TABLE "public"."user_product_reports"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_product_swipes" (
  "id_user"    uuid                     NOT NULL,
  "id_product" bigint                   NOT NULL,
  "swipe_type" text                     NOT NULL,
  "swiped_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_product_swipes_pkey" PRIMARY KEY (id_user, id_product)
);

ALTER TABLE "public"."user_product_swipes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_reports" (
  "id_report"        bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reported_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "reason"           text,
  "id_user_reporter" uuid                     NOT NULL,
  "id_user_reported" uuid                     NOT NULL,
  CONSTRAINT "user_reports_id_report_key" UNIQUE (id_report),
  CONSTRAINT "user_reports_pkey" PRIMARY KEY (id_user_reporter, id_user_reported)
);

ALTER TABLE "public"."user_reports"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user" (
  "id"                       uuid                     NOT NULL,
  "created_at"               timestamp with time zone NOT NULL DEFAULT now(),
  "username"                 text,
  "bio"                      text,
  "birth_date"               date,
  "gender"                   text,
  "profile_picture"          text,
  "profile_header"           text,
  "id_location"              bigint,
  "phone_number"             text,
  "trocoin_balance"          bigint                   NOT NULL DEFAULT '0'::bigint,
  "email"                    text,
  "has_completed_onboarding" boolean                  DEFAULT false,
  CONSTRAINT "user_email_key" UNIQUE (email),
  CONSTRAINT "user_pkey" PRIMARY KEY (id),
  CONSTRAINT "user_username_check" CHECK ((username ~ '^[a-zA-Z0-9_]{3,30}$'::text)),
  CONSTRAINT "user_username_format_check" CHECK ((username ~ '^[a-zA-Z0-9_]{3,30}$'::text)),
  CONSTRAINT "user_username_key" UNIQUE (username)
);

ALTER TABLE "public"."user"
  ENABLE ROW LEVEL SECURITY;

CREATE TYPE "public"."message_type" AS ENUM (
  'text',
  'troc_proposal'
);

ALTER TABLE "public"."message"
  ADD COLUMN "message_type" public.message_type NOT NULL DEFAULT 'text'::public.message_type;

CREATE OR REPLACE FUNCTION public.check_username_availability (
  candidate text
)
  RETURNS TABLE (
    available boolean,
    reason    text
  )
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  normalized text := lower(trim(candidate));
begin
  if normalized !~ '^[a-z0-9_]{3,30}$' then
    return query select false, 'format';
    return;
  end if;

  if exists (
    select 1
    from public.reserved_usernames r
    where lower(r.username) = normalized
  ) then
    return query select false, 'reserved';
    return;
  end if;

  if exists (
    select 1
    from public.user u
    where lower(u.username) = normalized
  ) then
    return query select false, 'taken';
    return;
  end if;

  return query select true, null::text;
end;
$function$;

CREATE OR REPLACE FUNCTION public.complete_onboarding (
  p_username        text,
  p_birth_date      date,
  p_gender          text,
  p_profile_picture text,
  p_latitude        double precision,
  p_longitude       double precision,
  p_category_ids    bigint[]
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
    v_user_id uuid;
    v_location_id bigint;
begin
    v_user_id := auth.uid();

    if v_user_id is null then
        raise exception 'Utilisateur non authentifié';
    end if;

    /*
     * La ligne public.user existe déjà grâce à handle_new_user.
     */
    select id_location
    into v_location_id
    from public."user"
    where id = v_user_id;

    if not found then
        raise exception 'Profil utilisateur introuvable';
    end if;

    /*
     * Création ou actualisation de la localisation.
     * PostGIS attend POINT(longitude latitude).
     */
    if p_latitude is not null and p_longitude is not null then
        if v_location_id is null then
            insert into public.user_location (location)
            values (
                extensions.st_setsrid(
                    extensions.st_makepoint(
                        p_longitude,
                        p_latitude
                    ),
                    4326
                )::extensions.geography
            )
            returning id into v_location_id;
        else
            update public.user_location
            set
                location = extensions.st_setsrid(
                    extensions.st_makepoint(
                        p_longitude,
                        p_latitude
                    ),
                    4326
                )::extensions.geography,
                last_updated = now()
            where id = v_location_id;
        end if;
    end if;

    /*
     * Mise à jour de la ligne créée par le trigger d'inscription.
     */
    update public."user"
    set
        username = lower(trim(p_username)),
        birth_date = p_birth_date,
        gender = nullif(trim(p_gender), ''),
        profile_picture = p_profile_picture,
        id_location = v_location_id,
        has_completed_onboarding = true
    where id = v_user_id;

    if not found then
        raise exception 'Profil utilisateur introuvable';
    end if;

    /*
     * Remplacement des préférences précédentes.
     */
    delete from public.user_category_preferences
    where id_user = v_user_id;

    insert into public.user_category_preferences (
        id_user,
        id_category
    )
    select
        v_user_id,
        selected.id_category
    from unnest(
        coalesce(p_category_ids, array[]::bigint[])
    ) as selected(id_category)
    on conflict (id_user, id_category) do nothing;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_product_transaction (
  p_owner_id    uuid,
  p_name        text,
  p_description text,
  p_category_id bigint,
  p_state_id    bigint,
  p_city        text,
  p_postcode    text,
  p_department  text,
  p_latitude    double precision,
  p_longitude   double precision,
  p_attributes  jsonb,
  p_photos      jsonb
)
  RETURNS bigint
  LANGUAGE plpgsql
  SET search_path TO 'pg_catalog', 'public', 'extensions'
  AS $function$
declare
  v_product_id bigint;
  v_attr jsonb;
  v_value text;
  v_allowed record;
  v_values text[];
  v_seen bigint[] := '{}';
  v_required_count integer;
  v_received_required_count integer;
  v_state_valid boolean;
  v_state_has_is_active boolean;
  v_photo jsonb;
  v_photo_position integer;
  v_photo_path text;
  v_photo_count integer;
  v_owner_text text;
begin
  v_owner_text := p_owner_id::text;

  if p_owner_id is null then
    raise exception 'OWNER_REQUIRED';
  end if;

  if p_name is null
     or btrim(p_name) = ''
     or char_length(btrim(p_name)) > 120 then
    raise exception 'INVALID_NAME';
  end if;

  if p_description is null
     or btrim(p_description) = ''
     or char_length(btrim(p_description)) > 5000 then
    raise exception 'INVALID_DESCRIPTION';
  end if;

  if p_city is null
     or btrim(p_city) = ''
     or char_length(btrim(p_city)) > 120 then
    raise exception 'INVALID_CITY';
  end if;

  if p_postcode is null
     or btrim(p_postcode) = ''
     or char_length(btrim(p_postcode)) > 20 then
    raise exception 'INVALID_POSTCODE';
  end if;

  if p_department is null
     or btrim(p_department) = ''
     or char_length(btrim(p_department)) > 120 then
    raise exception 'INVALID_DEPARTMENT';
  end if;

  if p_latitude is null
     or p_latitude <> p_latitude
     or p_latitude < -90
     or p_latitude > 90
     or p_longitude is null
     or p_longitude <> p_longitude
     or p_longitude < -180
     or p_longitude > 180 then
    raise exception 'INVALID_COORDINATES';
  end if;

  if p_attributes is null
     or jsonb_typeof(p_attributes) <> 'array' then
    raise exception 'INVALID_ATTRIBUTES_ARRAY';
  end if;

  if p_photos is null
     or jsonb_typeof(p_photos) <> 'array' then
    raise exception 'INVALID_PHOTOS_ARRAY';
  end if;

  v_photo_count := jsonb_array_length(p_photos);

  if v_photo_count < 1 or v_photo_count > 10 then
    raise exception 'INVALID_PHOTO_COUNT';
  end if;


  /*
    Vérification des photos :
    products/{ownerId}/{uploadUuid}/{position}.jpg
  */
  for v_photo in
    select value
    from jsonb_array_elements(p_photos)
  loop
    if jsonb_typeof(v_photo) <> 'object'
       or jsonb_typeof(v_photo->'path') <> 'string'
       or jsonb_typeof(v_photo->'position') <> 'number' then
      raise exception 'INVALID_PHOTO_OBJECT';
    end if;

    v_photo_path := v_photo->>'path';
    v_photo_position := (v_photo->>'position')::integer;

    if v_photo_position < 1
       or v_photo_position > v_photo_count then
      raise exception 'INVALID_PHOTO_POSITION';
    end if;

    if v_photo_path !~ (
      '^products/'
      || v_owner_text
      || '/[0-9a-fA-F-]{36}/'
      || v_photo_position::text
      || '\.jpg$'
    ) then
      raise exception 'INVALID_PHOTO_PATH';
    end if;
  end loop;

  if exists (
    select 1
    from jsonb_array_elements(p_photos) photo
    group by (photo->>'position')::integer
    having count(*) > 1
  ) then
    raise exception 'DUPLICATE_PHOTO_POSITION';
  end if;

  if (
    select count(*)
    from jsonb_array_elements(p_photos) photo
    where (photo->>'position')::integer
      between 1 and v_photo_count
  ) <> v_photo_count then
    raise exception 'PHOTO_POSITIONS_MUST_BE_CONTIGUOUS';
  end if;


  if not exists (
    select 1
    from public.category c
    where c.id = p_category_id
      and c.is_active = true
  ) then
    raise exception 'INVALID_CATEGORY';
  end if;


  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'state'
      and column_name = 'is_active'
  )
  into v_state_has_is_active;

  if v_state_has_is_active then
    execute '
      select exists (
        select 1
        from public.state
        where id = $1
          and is_active = true
      )
    '
    into v_state_valid
    using p_state_id;
  else
    select exists (
      select 1
      from public.state
      where id = p_state_id
    )
    into v_state_valid;
  end if;

  if not v_state_valid then
    raise exception 'INVALID_STATE';
  end if;


  /*
    Validation des attributs.
  */
  if exists (
    select 1
    from jsonb_array_elements(p_attributes) a
    where jsonb_typeof(a->'attributeId') <> 'number'
       or jsonb_typeof(a->'values') <> 'array'
  ) then
    raise exception 'INVALID_ATTRIBUTE_OBJECT';
  end if;

  select count(*)
  into v_required_count
  from public.category_attributes_resolved car
  where car.id_category = p_category_id
    and car.required = true;

  select count(*)
  into v_received_required_count
  from (
    select distinct
      (a->>'attributeId')::bigint as attribute_id
    from jsonb_array_elements(p_attributes) a
  ) received
  where exists (
    select 1
    from public.category_attributes_resolved car
    where car.id_category = p_category_id
      and car.required = true
      and car.id_attribute_def = received.attribute_id
  );

  if v_received_required_count <> v_required_count then
    raise exception 'REQUIRED_ATTRIBUTE_MISSING';
  end if;

  for v_attr in
    select value
    from jsonb_array_elements(p_attributes)
  loop
    if (v_attr->>'attributeId')::bigint = any(v_seen) then
      raise exception 'DUPLICATE_ATTRIBUTE';
    end if;

    v_seen := array_append(
      v_seen,
      (v_attr->>'attributeId')::bigint
    );

    select *
    into v_allowed
    from public.category_attributes_resolved car
    where car.id_category = p_category_id
      and car.id_attribute_def = (v_attr->>'attributeId')::bigint;

    if not found then
      raise exception 'ATTRIBUTE_NOT_ALLOWED';
    end if;

    select array_agg(value)
    into v_values
    from jsonb_array_elements_text(v_attr->'values') value;

    if v_values is null
       or cardinality(v_values) = 0 then
      raise exception 'ATTRIBUTE_VALUE_REQUIRED';
    end if;

    if v_allowed.input_type not in ('select', 'multi_select')
       and cardinality(v_values) <> 1 then
      raise exception 'TEXT_ATTRIBUTE_REQUIRES_ONE_VALUE';
    end if;

    if v_allowed.input_type in ('select', 'multi_select') then

      if coalesce(jsonb_typeof(v_allowed.options), 'null') <> 'array' then
        raise exception 'ATTRIBUTE_OPTIONS_MUST_BE_ARRAY';
      end if;

      if v_allowed.input_type = 'select'
         and cardinality(v_values) <> 1 then
        raise exception 'SELECT_REQUIRES_ONE_VALUE';
      end if;

      if v_allowed.input_type = 'multi_select'
         and cardinality(v_values) < 1 then
        raise exception 'MULTI_SELECT_REQUIRES_AT_LEAST_ONE_VALUE';
      end if;

      if exists (
        select 1
        from unnest(v_values) submitted_value
        where not exists (
          select 1
          from jsonb_array_elements_text(v_allowed.options) allowed_value
          where allowed_value = submitted_value
        )
      ) then
        raise exception 'ATTRIBUTE_VALUE_NOT_ALLOWED';
      end if;

    end if;
  end loop;


  insert into public.product (
    name,
    description,
    price_trocoin,
    is_active,
    id_state,
    id_category,
    id_user
  )
  values (
    btrim(p_name),
    btrim(p_description),
    0,
    false,
    p_state_id,
    p_category_id,
    p_owner_id
  )
  returning id into v_product_id;


  insert into public.product_location (
    product_id,
    location,
    city,
    postcode,
    department
  )
  values (
    v_product_id,
    extensions.st_setsrid(
      extensions.st_makepoint(
        p_longitude,
        p_latitude
      ),
      4326
    )::extensions.geography,
    btrim(p_city),
    btrim(p_postcode),
    btrim(p_department)
  );


  insert into public.product_attributes (
    id_product,
    id_attribute_def,
    product_attribute_value
  )
  select
    v_product_id,
    (attribute_json->>'attributeId')::bigint,
    value_text
  from jsonb_array_elements(p_attributes) attribute_json
  cross join lateral jsonb_array_elements_text(
    attribute_json->'values'
  ) value_text;


  insert into public.product_photos (
    url,
    order_position,
    id_product
  )
  select
    photo_json->>'path',
    (photo_json->>'position')::smallint,
    v_product_id
  from jsonb_array_elements(p_photos) photo_json;


  update public.product
  set is_active = true
  where id = v_product_id;

  return v_product_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.ensure_active_product_has_location()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path TO 'pg_catalog', 'public'
  AS $function$
declare
  v_product_id bigint;
begin
  if tg_table_name = 'product' then
    v_product_id := coalesce(
      (to_jsonb(new) ->> 'id')::bigint,
      (to_jsonb(old) ->> 'id')::bigint
    );

  elsif tg_table_name = 'product_location' then
    v_product_id := coalesce(
      (to_jsonb(new) ->> 'product_id')::bigint,
      (to_jsonb(old) ->> 'product_id')::bigint
    );

  else
    raise exception 'UNSUPPORTED_TRIGGER_TABLE'
      using errcode = '0A000';
  end if;

  if exists (
    select 1
    from public.product p
    where p.id = v_product_id
      and p.is_active = true
      and not exists (
        select 1
        from public.product_location pl
        where pl.product_id = p.id
      )
  ) then
    raise exception 'ACTIVE_PRODUCT_REQUIRES_LOCATION'
      using errcode = '23514';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_feed_filter_options (
  p_category_id bigint DEFAULT NULL::bigint
)
  RETURNS TABLE (
    kind         text,
    key          text,
    id           text,
    name         text,
    input_type   text,
    multiple     boolean,
    option_id    text,
    option_name  text,
    option_value text
  )
  LANGUAGE sql
  STABLE
  SET search_path TO 'pg_catalog', 'public'
  AS $function$
  WITH available_states AS (
    SELECT DISTINCT
      s.id::text AS id,
      s.name,
      s.slug
    FROM public.state AS s
    JOIN public.product AS p
      ON p.id_state = s.id
    WHERE p.is_active = true
      AND (p_category_id IS NULL OR p.id_category = p_category_id)
  ),
  resolved_attributes AS (
    SELECT DISTINCT
      ad.code,
      ad.id::text AS id,
      car.name,
      car.input_type,
      ad.options,
      CASE
        WHEN lower(coalesce(car.input_type, '')) IN (
          'multi_select', 'multiselect', 'checkbox', 'checkboxes',
          'checkbox_group', 'multi-checkbox', 'multi_checkbox'
        ) THEN true
        ELSE false
      END AS multiple
    FROM public.category_attributes_resolved AS car
    JOIN public.attributes_definitions AS ad
      ON ad.id = car.id_attribute_def
    WHERE p_category_id IS NOT NULL
      AND car.id_category = p_category_id
  )
  SELECT
    'condition'::text AS kind,
    'condition'::text AS key,
    st.id,
    st.name,
    'select'::text AS input_type,
    false AS multiple,
    NULL::text AS option_id,
    NULL::text AS option_name,
    NULL::text AS option_value
  FROM available_states AS st

  UNION ALL

  SELECT
    'attribute'::text AS kind,
    ra.code AS key,
    ra.id,
    ra.name,
    ra.input_type,
    ra.multiple,
    opt.value AS option_id,
    opt.value AS option_name,
    opt.value AS option_value
  FROM resolved_attributes AS ra
  LEFT JOIN LATERAL unnest(ra.options) AS opt(value)
    ON true
  ORDER BY kind, key, option_value NULLS FIRST;
$function$;

CREATE OR REPLACE FUNCTION public.get_product_locations_public (
  p_product_ids bigint[] DEFAULT NULL::bigint[],
  p_limit       integer  DEFAULT 100,
  p_offset      integer  DEFAULT 0
)
  RETURNS TABLE (
    product_id      bigint,
    city            text,
    postcode        text,
    department      text,
    distance_meters double precision
  )
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'public', 'extensions'
  AS $function$
  select
    p.id as product_id,
    pl.city,
    pl.postcode,
    pl.department,
    case
      when viewer.location is null then null::double precision
      else extensions.st_distance(pl.location, viewer.location)
    end as distance_meters
  from public.product p
  join public.product_location pl
    on pl.product_id = p.id
  left join lateral (
    select ul.location
    from public.user u
    join public.user_location ul
      on ul.id = u.id_location
    where u.id = auth.uid()
    limit 1
  ) viewer on true
  where p.is_active = true
    and (
      p_product_ids is null
      or p.id = any (p_product_ids)
    )
  order by
    case
      when viewer.location is null then null
      else extensions.st_distance(pl.location, viewer.location)
    end asc nulls last,
    p.id asc
  limit greatest(least(coalesce(p_limit, 100), 500), 1)
  offset greatest(coalesce(p_offset, 0), 0);
$function$;

CREATE OR REPLACE FUNCTION public.get_public_user_profile (
  p_username text
)
  RETURNS jsonb
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'public', 'extensions'
  AS $function$
  SELECT jsonb_build_object(
    'id', u.id,
    'username', u.username,
    'avatarUrl', u.profile_picture,
    'bannerUrl', u.profile_header,
    'bio', u.bio,
    'location', CASE
      WHEN ul.location IS NULL THEN NULL
      ELSE extensions.st_astext(ul.location)
    END,
    'createdAt', u.created_at,
    'trocsCount', (
      SELECT count(*)::integer
      FROM public.troc t
      WHERE t.status = 'completed'
        AND (
          t.id_user_initiator = u.id
          OR t.id_user_receiver = u.id
        )
    ),
    'followersCount', (
      SELECT count(*)::integer
      FROM public.user_follows uf
      WHERE uf.id_user_followed = u.id
    ),
    'followingCount', (
      SELECT count(*)::integer
      FROM public.user_follows uf
      WHERE uf.id_user_follower = u.id
    ),
    'reviewsCount', (
      SELECT count(*)::integer
      FROM public.user_evaluations ue
      WHERE ue.id_user_evaluated = u.id
    ),
    'reviewsRating', (
      SELECT round(avg(ue.rating)::numeric, 2)
      FROM public.user_evaluations ue
      WHERE ue.id_user_evaluated = u.id
    )
  )
  FROM public.user u
  LEFT JOIN public.user_location ul
    ON ul.id = u.id_location
  WHERE u.username = p_username;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$begin
  insert into public.user (id, email)
  values (new.id, new.email);
  return new;
end;$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_product_location_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path TO 'pg_catalog', 'public'
  AS $function$
begin
  new.updated_at := pg_catalog.now();
  return new;
end;
$function$;

ALTER TABLE "public"."brand_created_by"
  ADD CONSTRAINT "brand_created_by_id_brand_fkey" FOREIGN KEY (id_brand) REFERENCES public.brand(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."category"
  ADD CONSTRAINT "category_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."category_attribute_rules"
  ADD CONSTRAINT "category_attribute_rules_id_attribute_def_fkey" FOREIGN KEY (id_attribute_def) REFERENCES public.attributes_definitions(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."category_attribute_rules"
  ADD CONSTRAINT "category_attribute_rules_id_category_fkey" FOREIGN KEY (id_category) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."conversation_user"
  ADD CONSTRAINT "conversation_user_id_conversation_fkey" FOREIGN KEY (id_conversation) REFERENCES public.conversation(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."conversation_user"
  ADD CONSTRAINT "conversation_user_id_user_fkey" FOREIGN KEY (id_user) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."message"
  ADD CONSTRAINT "message_id_conversation_fkey" FOREIGN KEY (id_conversation) REFERENCES public.conversation(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."message_attachment"
  ADD CONSTRAINT "message_attachment_id_message_fkey" FOREIGN KEY (id_message) REFERENCES public.message(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."product"
  ADD CONSTRAINT "product_id_brand_fkey" FOREIGN KEY (id_brand) REFERENCES public.brand(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."product"
  ADD CONSTRAINT "product_id_category_fkey" FOREIGN KEY (id_category) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."feed_impressions"
  ADD CONSTRAINT "feed_impressions_id_product_fkey" FOREIGN KEY (id_product) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."product_attributes"
  ADD CONSTRAINT "product_attributes_id_attribute_def_fkey" FOREIGN KEY (id_attribute_def) REFERENCES public.attributes_definitions(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."product_attributes"
  ADD CONSTRAINT "product_attributes_id_product_fkey" FOREIGN KEY (id_product) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."product_location"
  ADD CONSTRAINT "product_location_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE;

ALTER TABLE "public"."product_photos"
  ADD CONSTRAINT "product_photos_id_product_fkey" FOREIGN KEY (id_product) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."product"
  ADD CONSTRAINT "product_id_state_fkey" FOREIGN KEY (id_state) REFERENCES public.state(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."message"
  ADD CONSTRAINT "message_id_troc_fkey" FOREIGN KEY (id_troc) REFERENCES public.troc(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."troc_product"
  ADD CONSTRAINT "troc_product_id_product_fkey" FOREIGN KEY (id_product) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."troc_product"
  ADD CONSTRAINT "troc_product_id_troc_fkey" FOREIGN KEY (id_troc) REFERENCES public.troc(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."troc_status_history"
  ADD CONSTRAINT "troc_status_history_id_troc_fkey" FOREIGN KEY (id_troc) REFERENCES public.troc(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user"
  ADD CONSTRAINT "user_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."brand_created_by"
  ADD CONSTRAINT "brand_created_by_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."feed_impressions"
  ADD CONSTRAINT "feed_impressions_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."message"
  ADD CONSTRAINT "message_id_sender_fkey" FOREIGN KEY (id_sender) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."notification"
  ADD CONSTRAINT "notification_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."product"
  ADD CONSTRAINT "product_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."troc"
  ADD CONSTRAINT "troc_id_user_initiator_fkey" FOREIGN KEY (id_user_initiator) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."troc"
  ADD CONSTRAINT "troc_id_user_receiver_fkey" FOREIGN KEY (id_user_receiver) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."trocoin_transaction"
  ADD CONSTRAINT "trocoin_transaction_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_blocks"
  ADD CONSTRAINT "user_blocks_id_user_blocked_fkey" FOREIGN KEY (id_user_blocked) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_blocks"
  ADD CONSTRAINT "user_blocks_id_user_blocker_fkey" FOREIGN KEY (id_user_blocker) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_category_preferences"
  ADD CONSTRAINT "user_category_preferences_id_category_fkey" FOREIGN KEY (id_category) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_category_preferences"
  ADD CONSTRAINT "user_category_preferences_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_certifications"
  ADD CONSTRAINT "user_certifications_id_certification_fkey" FOREIGN KEY (id_certification) REFERENCES public.certification(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_certifications"
  ADD CONSTRAINT "user_certifications_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_evaluations"
  ADD CONSTRAINT "user_evaluations_id_troc_fkey" FOREIGN KEY (id_troc) REFERENCES public.troc(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_evaluations"
  ADD CONSTRAINT "user_evaluations_id_user_evaluated_fkey" FOREIGN KEY (id_user_evaluated) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_evaluations"
  ADD CONSTRAINT "user_evaluations_id_user_evaluator_fkey" FOREIGN KEY (id_user_evaluator) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_follows"
  ADD CONSTRAINT "user_follows_id_user_followed_fkey" FOREIGN KEY (id_user_followed) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_follows"
  ADD CONSTRAINT "user_follows_id_user_follower_fkey" FOREIGN KEY (id_user_follower) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user"
  ADD CONSTRAINT "user_id_location_fkey" FOREIGN KEY (id_location) REFERENCES public.user_location(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_product_history"
  ADD CONSTRAINT "user_product_history_id_product_fkey" FOREIGN KEY (id_product) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_product_history"
  ADD CONSTRAINT "user_product_history_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_product_likes"
  ADD CONSTRAINT "user_product_likes_id_product_fkey" FOREIGN KEY (id_product) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_product_likes"
  ADD CONSTRAINT "user_product_likes_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_product_reports"
  ADD CONSTRAINT "user_product_reports_id_product_fkey" FOREIGN KEY (id_product) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_product_reports"
  ADD CONSTRAINT "user_product_reports_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_product_swipes"
  ADD CONSTRAINT "user_product_swipes_id_product_fkey" FOREIGN KEY (id_product) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_product_swipes"
  ADD CONSTRAINT "user_product_swipes_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_reports"
  ADD CONSTRAINT "user_reports_id_user_reported_fkey" FOREIGN KEY (id_user_reported) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_reports"
  ADD CONSTRAINT "user_reports_id_user_reporter_fkey" FOREIGN KEY (id_user_reporter) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE VIEW "public"."category_attributes_resolved" WITH (security_invoker=true) AS  WITH RECURSIVE category_ancestors AS (
         SELECT c.id AS id_category,
            c.id AS ancestor_id,
            c.parent_id,
            0 AS distance,
            ARRAY[c.id] AS visited
           FROM public.category c
        UNION ALL
         SELECT a.id_category,
            parent.id AS ancestor_id,
            parent.parent_id,
            (a.distance + 1),
            (a.visited || parent.id)
           FROM (category_ancestors a
             JOIN public.category parent ON ((parent.id = a.parent_id)))
          WHERE (NOT (parent.id = ANY (a.visited)))
        ), effective_rules AS (
         SELECT DISTINCT ON (a.id_category, r_1.id_attribute_def) a.id_category,
            r_1.id_attribute_def,
            r_1.required,
            a.ancestor_id AS source_category_id,
            a.distance
           FROM (category_ancestors a
             JOIN public.category_attribute_rules r_1 ON ((r_1.id_category = a.ancestor_id)))
          ORDER BY a.id_category, r_1.id_attribute_def, a.distance
        )
 SELECT r.id_category,
    d.id AS id_attribute_def,
    d.name,
    d.input_type,
    d.options,
    d.unit,
    r.required,
    r.source_category_id,
    (r.distance > 0) AS is_inherited
   FROM (effective_rules r
     JOIN public.attributes_definitions d ON ((d.id = r.id_attribute_def)));

CREATE UNIQUE INDEX attributes_definitions_code_uidx ON public.attributes_definitions USING btree (code);

CREATE INDEX idx_brand_created_by_id_user ON public.brand_created_by USING btree (id_user);

CREATE INDEX idx_category_attribute_rules_id_attribute_def ON public.category_attribute_rules USING btree (id_attribute_def);

CREATE INDEX idx_conversation_user_id_conversation ON public.conversation_user USING btree (id_conversation);

CREATE INDEX idx_message_attachment_id_message ON public.message_attachment USING btree (id_message);

CREATE INDEX idx_message_id_conversation ON public.message USING btree (id_conversation);

CREATE INDEX idx_message_id_sender ON public.message USING btree (id_sender);

CREATE INDEX idx_notification_id_user ON public.notification USING btree (id_user);

CREATE INDEX idx_product_attributes_id_attribute_def ON public.product_attributes USING btree (id_attribute_def);

CREATE INDEX idx_product_id_brand ON public.product USING btree (id_brand);

CREATE INDEX idx_product_id_category ON public.product USING btree (id_category);

CREATE INDEX idx_product_id_state ON public.product USING btree (id_state);

CREATE INDEX idx_product_id_user ON public.product USING btree (id_user);

CREATE INDEX idx_product_photos_id_product ON public.product_photos USING btree (id_product);

CREATE INDEX idx_troc_id_user_initiator ON public.troc USING btree (id_user_initiator);

CREATE INDEX idx_troc_id_user_receiver ON public.troc USING btree (id_user_receiver);

CREATE INDEX idx_troc_product_id_troc ON public.troc_product USING btree (id_troc);

CREATE INDEX idx_troc_status_history_id_troc ON public.troc_status_history USING btree (id_troc);

CREATE INDEX idx_trocoin_transaction_id_user ON public.trocoin_transaction USING btree (id_user);

CREATE INDEX idx_user_blocks_id_user_blocked ON public.user_blocks USING btree (id_user_blocked);

CREATE INDEX idx_user_category_preferences_id_category ON public.user_category_preferences USING btree (id_category);

CREATE INDEX idx_user_certifications_id_certification ON public.user_certifications USING btree (id_certification);

CREATE INDEX idx_user_evaluations_id_troc ON public.user_evaluations USING btree (id_troc);

CREATE INDEX idx_user_evaluations_id_user_evaluator ON public.user_evaluations USING btree (id_user_evaluator);

CREATE INDEX idx_user_follows_id_user_followed ON public.user_follows USING btree (id_user_followed);

CREATE INDEX idx_user_id_location ON public."user" USING btree (id_location);

CREATE INDEX idx_user_product_history_id_product ON public.user_product_history USING btree (id_product);

CREATE INDEX idx_user_product_likes_id_product ON public.user_product_likes USING btree (id_product);

CREATE INDEX idx_user_product_reports_id_product ON public.user_product_reports USING btree (id_product);

CREATE INDEX idx_user_product_swipes_id_product ON public.user_product_swipes USING btree (id_product);

CREATE INDEX idx_user_reports_id_user_reported ON public.user_reports USING btree (id_user_reported);

CREATE INDEX product_active_category_state_idx ON public.product USING btree (id_category, id_state)
  WHERE (is_active = true);

CREATE INDEX product_active_state_idx ON public.product USING btree (id_state)
  WHERE (is_active = true);

CREATE INDEX product_attributes_filter_idx ON public.product_attributes USING btree (id_attribute_def, product_attribute_value, id_product);

CREATE INDEX product_location_city_idx ON public.product_location USING btree (city);

CREATE INDEX product_location_location_gist_idx ON public.product_location USING gist (location);

CREATE INDEX product_location_postcode_idx ON public.product_location USING btree (postcode);

CREATE UNIQUE INDEX reserved_usernames_lower_idx ON public.reserved_usernames USING btree (lower(username));

CREATE UNIQUE INDEX user_username_lower_unique ON public."user" USING btree (lower(username));

CREATE UNIQUE INDEX user_username_unique_lower ON public."user" USING btree (lower(username));

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE CONSTRAINT TRIGGER product_requires_location
  AFTER INSERT OR UPDATE OF is_active ON public.product DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION public.ensure_active_product_has_location();

CREATE CONSTRAINT TRIGGER product_location_requires_product_location
  AFTER INSERT OR DELETE OR UPDATE ON public.product_location DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION public.ensure_active_product_has_location();

CREATE TRIGGER product_location_set_updated_at
  BEFORE UPDATE ON public.product_location
  FOR EACH ROW
  EXECUTE FUNCTION public.set_product_location_updated_at();

CREATE POLICY "Users can view attributes" ON "public"."attributes_definitions"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Everyone can view brands" ON "public"."brand"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Authenticated users can create a brand that doesn't exist" ON "public"."brand_created_by"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Everyone can view active categories" ON "public"."category"
  FOR SELECT
  TO PUBLIC
  USING ((is_active = true));

CREATE POLICY "Everyone can view active categories_attribute_rules" ON "public"."category_attribute_rules"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Everyone can view active certifications" ON "public"."certification"
  FOR SELECT
  TO PUBLIC
  USING ((is_active = true));

CREATE POLICY "Users can create conversations" ON "public"."conversation"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Users can view their conversations" ON "public"."conversation"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.conversation_user
  WHERE ((conversation_user.id_conversation = conversation.id) AND (conversation_user.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can join conversations" ON "public"."conversation_user"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can leave conversations" ON "public"."conversation_user"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can mute conversations they are part of" ON "public"."conversation_user"
  FOR UPDATE
  TO PUBLIC
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can view their conversations links" ON "public"."conversation_user"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can delete their own message" ON "public"."message"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_sender));

CREATE POLICY "Users can read their conversations messages" ON "public"."message"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.conversation_user
  WHERE ((conversation_user.id_conversation = message.id_conversation) AND (conversation_user.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can send messages" ON "public"."message"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_sender));

CREATE POLICY "Users can upload attachments to their own messages" ON "public"."message_attachment"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.message
  WHERE ((message.id = message_attachment.id_message) AND (message.id_sender = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can view attachments of their conversations" ON "public"."message_attachment"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM (public.message
     JOIN public.conversation_user ON ((conversation_user.id_conversation = message.id_conversation)))
  WHERE ((message.id = message_attachment.id_message) AND (conversation_user.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can read their own notifications" ON "public"."notification"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can update their own notifications (mark as read)" ON "public"."notification"
  FOR UPDATE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can create their own products" ON "public"."product"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can delete their own product" ON "public"."product"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can update their own product" ON "public"."product"
  FOR UPDATE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can view all products" ON "public"."product"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can add attributes to their own product" ON "public"."product_attributes"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.product
  WHERE ((product.id = product_attributes.id_product) AND (product.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can delete attributes from their own product" ON "public"."product_attributes"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.product
  WHERE ((product.id = product_attributes.id_product) AND (product.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can update attributes of their own product" ON "public"."product_attributes"
  FOR UPDATE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.product
  WHERE ((product.id = product_attributes.id_product) AND (product.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can view product attributes" ON "public"."product_attributes"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "product_location_owner_delete" ON "public"."product_location"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.product p
  WHERE ((p.id = product_location.product_id) AND (p.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "product_location_owner_insert" ON "public"."product_location"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.product p
  WHERE ((p.id = product_location.product_id) AND (p.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "product_location_owner_update" ON "public"."product_location"
  FOR UPDATE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.product p
  WHERE ((p.id = product_location.product_id) AND (p.id_user = ( SELECT auth.uid() AS uid))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.product p
  WHERE ((p.id = product_location.product_id) AND (p.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can delete photos of their own products" ON "public"."product_photos"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.product
  WHERE ((product.id = product_photos.id_product) AND (product.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can insert photos to their own products" ON "public"."product_photos"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.product
  WHERE ((product.id = product_photos.id_product) AND (product.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can update photos of their own products" ON "public"."product_photos"
  FOR UPDATE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.product
  WHERE ((product.id = product_photos.id_product) AND (product.id_user = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can view product photos" ON "public"."product_photos"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Everyone can read states" ON "public"."state"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can initiate trocs" ON "public"."troc"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user_initiator));

CREATE POLICY "Users can update trocs they initiated" ON "public"."troc"
  FOR UPDATE
  TO PUBLIC
  USING ((( SELECT auth.uid() AS uid) = id_user_initiator));

CREATE POLICY "Users can view their own trocs" ON "public"."troc"
  FOR SELECT
  TO "authenticated"
  USING (((( SELECT auth.uid() AS uid) = id_user_initiator) OR (( SELECT auth.uid() AS uid) = id_user_receiver)));

CREATE POLICY "Users can add their own products to trocs" ON "public"."troc_product"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_owner));

CREATE POLICY "Users can remove their own products from trocs" ON "public"."troc_product"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_owner));

CREATE POLICY "Users can view products of their trocs" ON "public"."troc_product"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.troc
  WHERE ((troc.id = troc_product.id_troc) AND ((( SELECT auth.uid() AS uid) = troc.id_user_initiator) OR (( SELECT auth.uid() AS uid) = troc.id_user_receiver))))));

CREATE POLICY "No deletes to status history" ON "public"."troc_status_history"
  FOR DELETE
  TO PUBLIC
  USING (false);

CREATE POLICY "No updates to status history" ON "public"."troc_status_history"
  FOR UPDATE
  TO PUBLIC
  USING (false);

CREATE POLICY "Users can view status history of their trocs" ON "public"."troc_status_history"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.troc
  WHERE ((troc.id = troc_status_history.id_troc) AND ((( SELECT auth.uid() AS uid) = troc.id_user_initiator) OR (( SELECT auth.uid() AS uid) = troc.id_user_receiver))))));

CREATE POLICY "Users can write history when they act on a troc" ON "public"."troc_status_history"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.troc
  WHERE ((troc.id = troc_status_history.id_troc) AND ((( SELECT auth.uid() AS uid) = troc.id_user_initiator) OR (( SELECT auth.uid() AS uid) = troc.id_user_receiver))))));

CREATE POLICY "Users can see transactions relevant to them" ON "public"."trocoin_transaction"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Public profiles are viewable by everyone" ON "public"."user"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can delete their own profile" ON "public"."user"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "Users can insert their own profile" ON "public"."user"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "Users can update own profile" ON "public"."user"
  FOR UPDATE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "Users can block others" ON "public"."user_blocks"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user_blocker));

CREATE POLICY "Users can unblock others" ON "public"."user_blocks"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user_blocker));

CREATE POLICY "Users can view who they have blocked" ON "public"."user_blocks"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user_blocker));

CREATE POLICY "Users can add category preferences" ON "public"."user_category_preferences"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can remove category preferences" ON "public"."user_category_preferences"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can view their category preferences" ON "public"."user_category_preferences"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Anyone can view public certifications of any user" ON "public"."user_certifications"
  FOR SELECT
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.certification
  WHERE ((certification.id = user_certifications.id_certification) AND (certification.is_public = true)))));

CREATE POLICY "Evaluations are publicly viewable" ON "public"."user_evaluations"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Evaluations cannot be updated" ON "public"."user_evaluations"
  FOR UPDATE
  TO PUBLIC
  USING (false);

CREATE POLICY "Users can delete their own evaluations" ON "public"."user_evaluations"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user_evaluator));

CREATE POLICY "Users can evaluate if they had a troc" ON "public"."user_evaluations"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((id_user_evaluator = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1
   FROM public.troc
  WHERE
    ((troc.id = user_evaluations.id_troc) AND (((troc.id_user_initiator = user_evaluations.id_user_evaluator) AND (troc.id_user_receiver = user_evaluations.id_user_evaluated)) OR
    ((troc.id_user_receiver = user_evaluations.id_user_evaluator) AND (troc.id_user_initiator = user_evaluations.id_user_evaluated))))))));

CREATE POLICY "Users can follow others" ON "public"."user_follows"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user_follower));

CREATE POLICY "Users can unfollow others" ON "public"."user_follows"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user_follower));

CREATE POLICY "Users can view their own follows" ON "public"."user_follows"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user_follower));

CREATE POLICY "Users can create a location" ON "public"."user_location"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Users can update their own location" ON "public"."user_location"
  FOR UPDATE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public."user"
  WHERE (("user".id_location = user_location.id) AND ("user".id = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can view others location" ON "public"."user_location"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Users can delete their product history" ON "public"."user_product_history"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can record product views" ON "public"."user_product_history"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can view their product history" ON "public"."user_product_history"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can like products" ON "public"."user_product_likes"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can unlike products" ON "public"."user_product_likes"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can view their product likes" ON "public"."user_product_likes"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can report products" ON "public"."user_product_reports"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can swipe products" ON "public"."user_product_swipes"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can view their swipes" ON "public"."user_product_swipes"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id_user));

CREATE POLICY "Users can report other users" ON "public"."user_reports"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = id_user_reporter));

CREATE POLICY "Users can insert their avatar" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH
    CHECK
    (((bucket_id = 'user-images'::text) AND ((storage.foldername(name))[1] = 'avatars'::text) AND ((storage.foldername(name))[2] = (auth.uid())::text) AND (storage.filename(name) =
    'avatar.jpg'::text)));

CREATE POLICY "Users can select their avatar" ON "storage"."objects"
  FOR SELECT
  TO "authenticated"
  USING
    (((bucket_id = 'user-images'::text) AND ((storage.foldername(name))[1] = 'avatars'::text) AND ((storage.foldername(name))[2] = (auth.uid())::text) AND (storage.filename(name) =
    'avatar.jpg'::text)));

CREATE POLICY "Users can update their avatar" ON "storage"."objects"
  FOR UPDATE
  TO "authenticated"
  USING
    (((bucket_id = 'user-images'::text) AND ((storage.foldername(name))[1] = 'avatars'::text) AND ((storage.foldername(name))[2] = (auth.uid())::text) AND (storage.filename(name) =
    'avatar.jpg'::text)))
  WITH
    CHECK
    (((bucket_id = 'user-images'::text) AND ((storage.foldername(name))[1] = 'avatars'::text) AND ((storage.foldername(name))[2] = (auth.uid())::text) AND (storage.filename(name) =
    'avatar.jpg'::text)));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."conversation";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."message_attachment";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."message";

COMMENT ON COLUMN "public"."attributes_definitions"."code" IS 'Stable technical key used by feed filters; must not depend on the displayed/translatable name.';

COMMENT ON COLUMN "public"."category"."parent_id" IS 'Une catégorie peut avoir 0 ou 1 parent, et 0 ou plusieurs enfants (Vêtements -> Pulls, Pantalons...)';

COMMENT ON COLUMN "public"."certification"."is_public" IS 'Allows to see the certification inside the app (paid certifications, enterprises, etc...)';

COMMENT ON COLUMN "public"."message"."message_type" IS 'Le type de message dans les MPs : text | troc_proposal | ou autres';

COMMENT ON COLUMN "public"."product"."share_count" IS 'Le nombre de fois que le produit (article) a été partagé';

COMMENT ON COLUMN "public"."troc"."status" IS 'draft        -- si on persiste les brouillons pending      -- proposition envoyée, attente de réponse accepted     -- acceptée, organisation de l’échange scheduled    -- rendez-vous/livraison défini completed    -- troc finalisé rejected     -- refusée cancelled    -- annulée par l’un des deux expired      -- expiration automatique éventuelle';

COMMENT ON EXTENSION "pgjwt" IS 'JSON Web Token API for Postgresql';

COMMENT ON EXTENSION "postgis" IS 'PostGIS geometry and geography spatial types and functions';

COMMENT ON TABLE "public"."attributes_definitions" IS 'All the different attributes available for a category (color, size, fabric, etc...)';

COMMENT ON TABLE "public"."category" IS 'Available categories for a product on Trocle';

COMMENT ON TABLE "public"."category_attribute_rules" IS 'Whether a category requires certain attribute';

COMMENT ON TABLE "public"."certification" IS 'Les certifications disponibles sur Trocle';

COMMENT ON TABLE "public"."conversation_user" IS 'Allows to know what user belongs to what conversation(s)';

COMMENT ON TABLE "public"."feed_impressions" IS '"Ce produit a réellement été affiché à l’utilisateur dans son feed, ce n''est pas un consultation (clic sur le produit)", pour ça, la table user_product_history existe';

COMMENT ON TABLE "public"."reserved_usernames" IS 'Pseudos réservés (admin, shop etc)';

COMMENT ON TABLE "public"."state" IS 'State of a product';

COMMENT ON TABLE "public"."user_category_preferences" IS 'Product categories preferred by a user on Trocle';

GRANT EXECUTE ON FUNCTION "public"."check_username_availability"(text) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."complete_onboarding"(text, date, text, text, double precision, double precision, bigint[]) FROM PUBLIC;

GRANT EXECUTE
  ON FUNCTION "public"."complete_onboarding"(text, date, text, text, double precision, double precision, bigint[])
  TO "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."create_product_transaction"(uuid, text, text, bigint, bigint, text, text, text, double precision, double precision, jsonb, jsonb) FROM PUBLIC;

GRANT EXECUTE
  ON FUNCTION "public"."create_product_transaction"(uuid, text, text, bigint, bigint, text, text, text, double precision, double precision, jsonb, jsonb)
  TO "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."ensure_active_product_has_location"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."ensure_active_product_has_location"() TO "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."get_feed_filter_options"(bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_feed_filter_options"(bigint) TO "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."get_product_locations_public"(bigint[], integer, integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_product_locations_public"(bigint[], integer, integer) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."get_public_user_profile"(text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_public_user_profile"(text) TO "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."set_product_location_updated_at"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."set_product_location_updated_at"() TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."attributes_definitions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."brand" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."brand_created_by" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."category" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."category_attribute_rules" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."certification" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversation" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversation_user" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."feed_impressions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."keep_alive" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."message" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."message_attachment" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notification" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."product" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."product_attributes" TO "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON TABLE "public"."product_location" FROM "authenticated";

GRANT DELETE, INSERT, UPDATE ON TABLE "public"."product_location" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."product_location" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."product_photos" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reserved_usernames" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."state" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."troc" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."troc_product" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."troc_status_history" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."trocoin_transaction" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_blocks" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_category_preferences" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_certifications" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_evaluations" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_follows" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_location" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_product_history" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_product_likes" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_product_reports" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_product_swipes" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_reports" TO "anon", "authenticated", "postgres", "service_role";

GRANT USAGE ON TYPE "public"."message_type" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE "public"."category_attributes_resolved"
  TO "anon", "authenticated", "postgres", "service_role";

